graph [
        directed 1
        node [
               id 0
               label "0"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 0
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 0
               Kit 1
               Lat 0
               Lck 0
               Lef1 0
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 1
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 0
               Tcrb 0
               Zap70 0
        ]
        node [
               id 1
               label "1"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 1
               Lef1 0
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 2
               label "2"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 3
               label "3"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 4
               label "4"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 0
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 0
               Lck 1
               Lef1 1
               Lmo2 1
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 5
               label "5"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 6
               label "6"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 7
               label "7"
               Bcl11b 1
               Cd3e 1
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 8
               label "8"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 1
               Lef1 0
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 9
               label "9"
               Bcl11b 1
               Cd3e 1
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 10
               label "10"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 0
               Lmo2 0
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 11
               label "11"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 12
               label "12"
               Bcl11b 1
               Cd3e 1
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 13
               label "13"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 14
               label "14"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 0
               Lef1 0
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 15
               label "15"
               Bcl11b 1
               Cd3e 1
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 16
               label "16"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 0
               Lef1 0
               Lmo2 1
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 17
               label "17"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 18
               label "18"
               Bcl11b 1
               Cd3e 0
               Cd3g 1
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 1
               Lef1 0
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 19
               label "19"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 0
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 20
               label "20"
               Bcl11b 1
               Cd3e 0
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 21
               label "21"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 0
               Lef1 1
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 22
               label "22"
               Bcl11b 1
               Cd3e 0
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 23
               label "23"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 1
               Lef1 1
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 24
               label "24"
               Bcl11b 1
               Cd3e 0
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 25
               label "25"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 0
               Lef1 0
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 26
               label "26"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 27
               label "27"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 0
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 28
               label "28"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 0
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 29
               label "29"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 30
               label "30"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 1
               Lef1 0
               Lmo2 0
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 31
               label "31"
               Bcl11b 1
               Cd3e 0
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 32
               label "32"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 0
               Lef1 0
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 33
               label "33"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 34
               label "34"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 35
               label "35"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 0
               Lef1 1
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 36
               label "36"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 37
               label "37"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 1
               Lef1 1
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 38
               label "38"
               Bcl11b 1
               Cd3e 0
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 39
               label "39"
               Bcl11b 1
               Cd3e 1
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 0
               Lef1 1
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 40
               label "40"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 41
               label "41"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 0
               Lmo2 0
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 42
               label "42"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 43
               label "43"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 0
               Lck 1
               Lef1 0
               Lmo2 1
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 44
               label "44"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 0
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 45
               label "45"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 46
               label "46"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 1
               Lef1 1
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 47
               label "47"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 48
               label "48"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 0
               Lck 0
               Lef1 1
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 49
               label "49"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 0
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 50
               label "50"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 51
               label "51"
               Bcl11b 1
               Cd3e 1
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 52
               label "52"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 0
               Lck 1
               Lef1 0
               Lmo2 1
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 53
               label "53"
               Bcl11b 1
               Cd3e 0
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 0
        ]
        node [
               id 54
               label "54"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 0
               Lck 1
               Lef1 1
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 55
               label "55"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 56
               label "56"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 0
               Lmo2 1
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 57
               label "57"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 58
               label "58"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 0
               Lef1 0
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 59
               label "59"
               Bcl11b 1
               Cd3e 1
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 60
               label "60"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 0
               Lef1 0
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 61
               label "61"
               Bcl11b 1
               Cd3e 1
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 62
               label "62"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 0
               Lmo2 0
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 63
               label "63"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 64
               label "64"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 0
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 0
               Lef1 0
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 65
               label "65"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 66
               label "66"
               Bcl11b 1
               Cd3e 0
               Cd3g 1
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 0
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 67
               label "67"
               Bcl11b 1
               Cd3e 1
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 68
               label "68"
               Bcl11b 1
               Cd3e 1
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 0
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 69
               label "69"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 0
               Lef1 0
               Lmo2 1
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 70
               label "70"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 71
               label "71"
               Bcl11b 1
               Cd3e 0
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 72
               label "72"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 0
               Lef1 0
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 73
               label "73"
               Bcl11b 1
               Cd3e 0
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 74
               label "74"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 75
               label "75"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 76
               label "76"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 0
               Lef1 1
               Lmo2 1
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 77
               label "77"
               Bcl11b 1
               Cd3e 0
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 78
               label "78"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 79
               label "79"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 0
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 80
               label "80"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 0
               Lck 0
               Lef1 0
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 81
               label "81"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 82
               label "82"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 1
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 83
               label "83"
               Bcl11b 1
               Cd3e 0
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 84
               label "84"
               Bcl11b 1
               Cd3e 0
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 0
        ]
        edge [
               source 7
               target 3
               frequency 1
        ]
        edge [
               source 40
               target 3
               frequency 1
        ]
        edge [
               source 58
               target 59
               frequency 1
        ]
        edge [
               source 54
               target 55
               frequency 1
        ]
        edge [
               source 74
               target 75
               frequency 1
        ]
        edge [
               source 0
               target 76
               frequency 1
        ]
        edge [
               source 72
               target 73
               frequency 1
        ]
        edge [
               source 0
               target 10
               frequency 1
        ]
        edge [
               source 0
               target 53
               frequency 1
        ]
        edge [
               source 80
               target 81
               frequency 1
        ]
        edge [
               source 0
               target 32
               frequency 1
        ]
        edge [
               source 6
               target 7
               frequency 1
        ]
        edge [
               source 44
               target 45
               frequency 1
        ]
        edge [
               source 25
               target 26
               frequency 1
        ]
        edge [
               source 68
               target 3
               frequency 1
        ]
        edge [
               source 0
               target 4
               frequency 1
        ]
        edge [
               source 35
               target 36
               frequency 1
        ]
        edge [
               source 22
               target 3
               frequency 1
        ]
        edge [
               source 71
               target 3
               frequency 1
        ]
        edge [
               source 0
               target 58
               frequency 1
        ]
        edge [
               source 21
               target 59
               frequency 1
        ]
        edge [
               source 4
               target 5
               frequency 1
        ]
        edge [
               source 9
               target 3
               frequency 1
        ]
        edge [
               source 0
               target 80
               frequency 1
        ]
        edge [
               source 14
               target 15
               frequency 1
        ]
        edge [
               source 61
               target 3
               frequency 1
        ]
        edge [
               source 0
               target 30
               frequency 1
        ]
        edge [
               source 0
               target 1
               frequency 1
        ]
        edge [
               source 0
               target 52
               frequency 1
        ]
        edge [
               source 47
               target 3
               frequency 1
        ]
        edge [
               source 0
               target 39
               frequency 1
        ]
        edge [
               source 83
               target 3
               frequency 1
        ]
        edge [
               source 46
               target 47
               frequency 1
        ]
        edge [
               source 0
               target 27
               frequency 1
        ]
        edge [
               source 0
               target 64
               frequency 1
        ]
        edge [
               source 20
               target 3
               frequency 1
        ]
        edge [
               source 69
               target 70
               frequency 1
        ]
        edge [
               source 0
               target 14
               frequency 1
        ]
        edge [
               source 73
               target 3
               frequency 1
        ]
        edge [
               source 0
               target 49
               frequency 1
        ]
        edge [
               source 59
               target 3
               frequency 2
        ]
        edge [
               source 0
               target 21
               frequency 2
        ]
        edge [
               source 13
               target 3
               frequency 3
        ]
        edge [
               source 12
               target 13
               frequency 1
        ]
        edge [
               source 0
               target 62
               frequency 1
        ]
        edge [
               source 16
               target 17
               frequency 1
        ]
        edge [
               source 0
               target 84
               frequency 1
        ]
        edge [
               source 37
               target 38
               frequency 1
        ]
        edge [
               source 0
               target 18
               frequency 1
        ]
        edge [
               source 38
               target 3
               frequency 1
        ]
        edge [
               source 33
               target 3
               frequency 1
        ]
        edge [
               source 0
               target 74
               frequency 1
        ]
        edge [
               source 0
               target 8
               frequency 1
        ]
        edge [
               source 23
               target 24
               frequency 1
        ]
        edge [
               source 77
               target 3
               frequency 1
        ]
        edge [
               source 0
               target 46
               frequency 1
        ]
        edge [
               source 11
               target 3
               frequency 3
        ]
        edge [
               source 49
               target 50
               frequency 1
        ]
        edge [
               source 76
               target 77
               frequency 1
        ]
        edge [
               source 0
               target 68
               frequency 1
        ]
        edge [
               source 63
               target 3
               frequency 1
        ]
        edge [
               source 50
               target 3
               frequency 1
        ]
        edge [
               source 28
               target 29
               frequency 1
        ]
        edge [
               source 0
               target 56
               frequency 1
        ]
        edge [
               source 0
               target 43
               frequency 1
        ]
        edge [
               source 30
               target 31
               frequency 1
        ]
        edge [
               source 36
               target 3
               frequency 1
        ]
        edge [
               source 0
               target 28
               frequency 1
        ]
        edge [
               source 32
               target 33
               frequency 1
        ]
        edge [
               source 26
               target 3
               frequency 1
        ]
        edge [
               source 75
               target 3
               frequency 1
        ]
        edge [
               source 0
               target 37
               frequency 1
        ]
        edge [
               source 29
               target 3
               frequency 1
        ]
        edge [
               source 78
               target 3
               frequency 1
        ]
        edge [
               source 60
               target 71
               frequency 1
        ]
        edge [
               source 39
               target 40
               frequency 1
        ]
        edge [
               source 65
               target 3
               frequency 1
        ]
        edge [
               source 43
               target 5
               frequency 1
        ]
        edge [
               source 0
               target 25
               frequency 1
        ]
        edge [
               source 15
               target 3
               frequency 1
        ]
        edge [
               source 82
               target 83
               frequency 1
        ]
        edge [
               source 0
               target 12
               frequency 1
        ]
        edge [
               source 41
               target 42
               frequency 1
        ]
        edge [
               source 2
               target 3
               frequency 1
        ]
        edge [
               source 0
               target 34
               frequency 1
        ]
        edge [
               source 5
               target 3
               frequency 2
        ]
        edge [
               source 8
               target 9
               frequency 1
        ]
        edge [
               source 0
               target 19
               frequency 1
        ]
        edge [
               source 0
               target 6
               frequency 1
        ]
        edge [
               source 24
               target 3
               frequency 1
        ]
        edge [
               source 17
               target 3
               frequency 1
        ]
        edge [
               source 51
               target 13
               frequency 1
        ]
        edge [
               source 0
               target 69
               frequency 1
        ]
        edge [
               source 27
               target 3
               frequency 1
        ]
        edge [
               source 0
               target 60
               frequency 3
        ]
        edge [
               source 10
               target 11
               frequency 1
        ]
        edge [
               source 79
               target 3
               frequency 1
        ]
        edge [
               source 34
               target 11
               frequency 1
        ]
        edge [
               source 0
               target 82
               frequency 1
        ]
        edge [
               source 0
               target 16
               frequency 1
        ]
        edge [
               source 66
               target 3
               frequency 1
        ]
        edge [
               source 0
               target 72
               frequency 1
        ]
        edge [
               source 48
               target 13
               frequency 1
        ]
        edge [
               source 1
               target 2
               frequency 1
        ]
        edge [
               source 0
               target 54
               frequency 1
        ]
        edge [
               source 3
               target 3
               frequency 50
        ]
        edge [
               source 52
               target 3
               frequency 1
        ]
        edge [
               source 60
               target 67
               frequency 1
        ]
        edge [
               source 0
               target 44
               frequency 1
        ]
        edge [
               source 56
               target 57
               frequency 1
        ]
        edge [
               source 55
               target 3
               frequency 1
        ]
        edge [
               source 0
               target 78
               frequency 1
        ]
        edge [
               source 42
               target 3
               frequency 1
        ]
        edge [
               source 0
               target 66
               frequency 1
        ]
        edge [
               source 84
               target 45
               frequency 1
        ]
        edge [
               source 45
               target 3
               frequency 2
        ]
        edge [
               source 60
               target 61
               frequency 1
        ]
        edge [
               source 0
               target 51
               frequency 1
        ]
        edge [
               source 81
               target 3
               frequency 1
        ]
        edge [
               source 62
               target 63
               frequency 1
        ]
        edge [
               source 0
               target 41
               frequency 1
        ]
        edge [
               source 31
               target 3
               frequency 1
        ]
        edge [
               source 19
               target 20
               frequency 1
        ]
        edge [
               source 0
               target 23
               frequency 1
        ]
        edge [
               source 64
               target 65
               frequency 1
        ]
        edge [
               source 18
               target 3
               frequency 1
        ]
        edge [
               source 67
               target 3
               frequency 1
        ]
        edge [
               source 0
               target 79
               frequency 1
        ]
        edge [
               source 21
               target 22
               frequency 1
        ]
        edge [
               source 70
               target 3
               frequency 1
        ]
        edge [
               source 0
               target 48
               frequency 1
        ]
        edge [
               source 53
               target 11
               frequency 1
        ]
        edge [
               source 0
               target 35
               frequency 1
        ]
        edge [
               source 57
               target 3
               frequency 1
        ]
]