graph [
        directed 1
        name "# -----------------------------------------------------------------------------
# BOOLEAN NETWORK DEFINITION
#
# Model         T cell development gene regulatory network
# Description   
#
# Author        Matthew Langley
# Date          14 February 2017
# -----------------------------------------------------------------------------

INPUT_DL4 = True
INPUT_IL7 = True
INPUT_TCR = False

NOTCH_SIGNALING = True
IL7_SIGNALING = True
TCR_SIGNALING = False
E_PROTEIN = True

Bcl11b = False
Cd3e = False
Cd3g = False
Cebpa = False
Deltex = False
E2a = True
Ebf1 = False
Ets1 = False
Gata3 = False
Gfi1 = True
Gfi1b = True
HEB = True
Hes1 = True
Hhex = True
Id3 = False
Ikaros = True
Il7ra = False
Kit = True
Lat = False
Lck = False
Lef1 = False
Lmo2 = True
Lyl1 = True
Myb = True
Notch1 = True
Ptcra = False
Pu1 = True
Rag1 = False
Runx1 = True
Scl = True
Tcf7 = False
Tcrb = False
Zap70 = False
# -----------------------------------------------------------------------------
# BOOLEAN NETWORK DEFINITION
#
# Model         T cell development gene regulatory network
# Description   
#
# Author        Matthew Langley
# Date          14 February 2017
# -----------------------------------------------------------------------------

NOTCH_SIGNALING *= INPUT_DL4 and Notch1
IL7_SIGNALING *= INPUT_IL7 and Il7ra
TCR_SIGNALING *= INPUT_TCR and Cd3e and Cd3g and Ptcra and Tcrb and Lck and Zap70
E_PROTEIN *= E2a and HEB and not Id3

INPUT_DL4 *= INPUT_DL4
INPUT_IL7 *= INPUT_IL7
INPUT_TCR *= INPUT_TCR

Bcl11b *= NOTCH_SIGNALING and Gata3 and Tcf7 and Runx1
Cd3e *= (NOTCH_SIGNALING and Bcl11b and (Gata3 or Ikaros or Tcf7)) and not Pu1
Cd3g *= (NOTCH_SIGNALING and Bcl11b and (Gata3 or Ikaros or Tcf7)) and not Pu1
Cebpa *= IL7_SIGNALING and not NOTCH_SIGNALING and not Bcl11b and not Gata3
Deltex *= NOTCH_SIGNALING and Gata3
E2a *= E2a
Ebf1 *= (IL7_SIGNALING and E2a) and not NOTCH_SIGNALING
Ets1 *= (TCR_SIGNALING or (Runx1 and Scl)) and not Pu1
Gata3 *= (((NOTCH_SIGNALING or IL7_SIGNALING) and E_PROTEIN and Myb) or Tcf7 or Runx1) and not (Pu1 and not (NOTCH_SIGNALING or Myb))
Gfi1 *= E_PROTEIN and (not Pu1 or not Gfi1b)
Gfi1b *= (NOTCH_SIGNALING or E_PROTEIN) and not Bcl11b
HEB *= HEB or Scl
Hes1 *= (NOTCH_SIGNALING or (E_PROTEIN and not Pu1)) and not (Ikaros and TCR_SIGNALING)
Hhex *= Scl and Lmo2
Id3 *= TCR_SIGNALING or (Scl and Lyl1 and not NOTCH_SIGNALING and not Bcl11b and not Gata3 and not Ebf1 and not Pu1)
Ikaros *= Ikaros or not Pu1
Il7ra *= NOTCH_SIGNALING or E_PROTEIN or (Pu1 and not Gata3)
Kit *= (IL7_SIGNALING and (Scl or Lmo2)) and not Bcl11b
Lat *= (NOTCH_SIGNALING and E_PROTEIN) and not Pu1
Lck *= NOTCH_SIGNALING and (not IL7_SIGNALING or not Pu1)
Lef1 *= NOTCH_SIGNALING and Tcf7
Lmo2 *= Pu1
Lyl1 *= Lmo2 and Pu1
Myb *= Scl or not Pu1 or TCR_SIGNALING
Notch1 *= E_PROTEIN
Ptcra *= (E_PROTEIN and NOTCH_SIGNALING and Bcl11b and Myb) and (not IL7_SIGNALING or not (Scl and Lyl1) or not Gata3) and not (Ikaros and TCR_SIGNALING)
Pu1 *= IL7_SIGNALING and not Gata3 and not Gfi1 and not Runx1 and not Tcf7 and not Bcl11b
Rag1 *= (E_PROTEIN and NOTCH_SIGNALING and Gfi1) and not Pu1
Runx1 *= NOTCH_SIGNALING and not (Ikaros and TCR_SIGNALING)
Scl *= E2a or Gata3 or Gfi1 or Pu1	
Tcf7 *= NOTCH_SIGNALING or (Tcf7 and not Gata3) or TCR_SIGNALING
Tcrb *=  Ets1 and Gata3 and Runx1 and NOTCH_SIGNALING
Zap70 *= TCR_SIGNALING or not Pu1"
        node [
               id 0
               label "0"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 0
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 0
               Kit 1
               Lat 0
               Lck 0
               Lef1 0
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 1
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 0
               Tcrb 0
               Zap70 0
        ]
        node [
               id 1
               label "1"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 0
               Lck 0
               Lef1 1
               Lmo2 1
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 2
               label "2"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 3
               label "3"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 4
               label "4"
               Bcl11b 1
               Cd3e 0
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 0
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 5
               label "5"
               Bcl11b 1
               Cd3e 0
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 0
               Lck 1
               Lef1 1
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 6
               label "6"
               Bcl11b 1
               Cd3e 0
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 0
               Lck 1
               Lef1 1
               Lmo2 1
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 7
               label "7"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 0
               Lef1 0
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 8
               label "8"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 9
               label "9"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 1
               Lef1 1
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 10
               label "10"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 11
               label "11"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 0
               Lck 1
               Lef1 1
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 12
               label "12"
               Bcl11b 1
               Cd3e 0
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 13
               label "13"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 0
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 14
               label "14"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 0
               Lef1 0
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 15
               label "15"
               Bcl11b 1
               Cd3e 0
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 16
               label "16"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 1
               Lef1 0
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 17
               label "17"
               Bcl11b 1
               Cd3e 0
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 18
               label "18"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 0
               Lck 1
               Lef1 0
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 19
               label "19"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 20
               label "20"
               Bcl11b 1
               Cd3e 1
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 0
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 21
               label "21"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 22
               label "22"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 23
               label "23"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 24
               label "24"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 25
               label "25"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 26
               label "26"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 27
               label "27"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 0
               Lmo2 1
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 28
               label "28"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 0
               Lck 0
               Lef1 0
               Lmo2 0
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 29
               label "29"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 30
               label "30"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 0
               Lck 1
               Lef1 1
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 31
               label "31"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 32
               label "32"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 0
               Lef1 1
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 33
               label "33"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 34
               label "34"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 1
               Lef1 0
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 35
               label "35"
               Bcl11b 1
               Cd3e 1
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 36
               label "36"
               Bcl11b 1
               Cd3e 0
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 1
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 37
               label "37"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 0
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 38
               label "38"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 39
               label "39"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 40
               label "40"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 1
               Lef1 0
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 41
               label "41"
               Bcl11b 1
               Cd3e 1
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 42
               label "42"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 1
               Lef1 1
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 43
               label "43"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 44
               label "44"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 0
               Lmo2 1
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 45
               label "45"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 46
               label "46"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 0
               Lck 1
               Lef1 0
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 47
               label "47"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 0
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 48
               label "48"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 49
               label "49"
               Bcl11b 1
               Cd3e 1
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 50
               label "50"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 51
               label "51"
               Bcl11b 1
               Cd3e 1
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 52
               label "52"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 0
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 0
               Lck 1
               Lef1 0
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 53
               label "53"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 0
               Lmo2 1
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 54
               label "54"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 55
               label "55"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 0
               Lef1 1
               Lmo2 0
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 56
               label "56"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 0
               Lef1 1
               Lmo2 0
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 0
        ]
        node [
               id 57
               label "57"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 58
               label "58"
               Bcl11b 1
               Cd3e 0
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 0
               Lck 1
               Lef1 1
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 59
               label "59"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 1
               Lef1 0
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 60
               label "60"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 61
               label "61"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 0
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 62
               label "62"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 63
               label "63"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 0
               Lef1 1
               Lmo2 0
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 64
               label "64"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 0
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 65
               label "65"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 0
               Lck 1
               Lef1 0
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 66
               label "66"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 1
               Lef1 0
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 67
               label "67"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 68
               label "68"
               Bcl11b 1
               Cd3e 1
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 0
               Lef1 1
               Lmo2 1
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 69
               label "69"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 70
               label "70"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 0
               Lck 1
               Lef1 1
               Lmo2 1
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 71
               label "71"
               Bcl11b 1
               Cd3e 0
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 72
               label "72"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 0
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 0
               Lck 1
               Lef1 1
               Lmo2 1
               Lyl1 1
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 73
               label "73"
               Bcl11b 1
               Cd3e 1
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 74
               label "74"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 0
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 1
               Lck 0
               Lef1 0
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 0
        ]
        node [
               id 75
               label "75"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        node [
               id 76
               label "76"
               Bcl11b 1
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 0
               Gata3 1
               Gfi1 0
               Gfi1b 0
               HEB 1
               Hes1 1
               Hhex 0
               IL7SIGNALING 0
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 0
               Lat 0
               Lck 1
               Lef1 0
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 0
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 77
               label "77"
               Bcl11b 0
               Cd3e 0
               Cd3g 0
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 0
               Lck 1
               Lef1 0
               Lmo2 1
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 0
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 0
               Zap70 1
        ]
        node [
               id 78
               label "78"
               Bcl11b 1
               Cd3e 0
               Cd3g 1
               Cebpa 0
               Deltex 1
               E2a 1
               EPROTEIN 1
               Ebf1 0
               Ets1 1
               Gata3 1
               Gfi1 1
               Gfi1b 1
               HEB 1
               Hes1 1
               Hhex 1
               IL7SIGNALING 1
               INPUTDL4 1
               INPUTIL7 1
               INPUTTCR 0
               Id3 0
               Ikaros 1
               Il7ra 1
               Kit 1
               Lat 1
               Lck 1
               Lef1 1
               Lmo2 0
               Lyl1 0
               Myb 1
               NOTCHSIGNALING 1
               Notch1 1
               Ptcra 1
               Pu1 0
               Rag1 1
               Runx1 1
               Scl 1
               TCRSIGNALING 0
               Tcf7 1
               Tcrb 1
               Zap70 1
        ]
        edge [
               source 0
               target 20
               weight 1
        ]
        edge [
               source 0
               target 7
               weight 1
        ]
        edge [
               source 0
               target 76
               weight 1
        ]
        edge [
               source 40
               target 41
               weight 1
        ]
        edge [
               source 18
               target 19
               weight 1
        ]
        edge [
               source 65
               target 39
               weight 1
        ]
        edge [
               source 74
               target 75
               weight 1
        ]
        edge [
               source 0
               target 61
               weight 1
        ]
        edge [
               source 0
               target 32
               weight 1
        ]
        edge [
               source 44
               target 45
               weight 1
        ]
        edge [
               source 55
               target 8
               weight 1
        ]
        edge [
               source 25
               target 26
               weight 1
        ]
        edge [
               source 61
               target 62
               weight 1
        ]
        edge [
               source 19
               target 3
               weight 2
        ]
        edge [
               source 0
               target 4
               weight 1
        ]
        edge [
               source 0
               target 55
               weight 1
        ]
        edge [
               source 22
               target 3
               weight 1
        ]
        edge [
               source 71
               target 3
               weight 1
        ]
        edge [
               source 0
               target 58
               weight 1
        ]
        edge [
               source 14
               target 15
               weight 1
        ]
        edge [
               source 0
               target 30
               weight 1
        ]
        edge [
               source 0
               target 1
               weight 1
        ]
        edge [
               source 72
               target 73
               weight 1
        ]
        edge [
               source 63
               target 29
               weight 1
        ]
        edge [
               source 0
               target 52
               weight 1
        ]
        edge [
               source 0
               target 6
               weight 1
        ]
        edge [
               source 0
               target 42
               weight 1
        ]
        edge [
               source 34
               target 35
               weight 1
        ]
        edge [
               source 7
               target 8
               weight 1
        ]
        edge [
               source 37
               target 3
               weight 1
        ]
        edge [
               source 0
               target 27
               weight 1
        ]
        edge [
               source 0
               target 64
               weight 1
        ]
        edge [
               source 20
               target 3
               weight 1
        ]
        edge [
               source 0
               target 14
               weight 2
        ]
        edge [
               source 73
               target 3
               weight 2
        ]
        edge [
               source 0
               target 36
               weight 1
        ]
        edge [
               source 10
               target 3
               weight 1
        ]
        edge [
               source 0
               target 21
               weight 1
        ]
        edge [
               source 13
               target 3
               weight 1
        ]
        edge [
               source 62
               target 3
               weight 1
        ]
        edge [
               source 0
               target 77
               weight 1
        ]
        edge [
               source 64
               target 39
               weight 1
        ]
        edge [
               source 0
               target 11
               weight 1
        ]
        edge [
               source 49
               target 3
               weight 1
        ]
        edge [
               source 66
               target 67
               weight 1
        ]
        edge [
               source 16
               target 17
               weight 1
        ]
        edge [
               source 35
               target 3
               weight 1
        ]
        edge [
               source 0
               target 18
               weight 1
        ]
        edge [
               source 33
               target 3
               weight 2
        ]
        edge [
               source 50
               target 51
               weight 1
        ]
        edge [
               source 0
               target 74
               weight 1
        ]
        edge [
               source 23
               target 24
               weight 1
        ]
        edge [
               source 8
               target 3
               weight 3
        ]
        edge [
               source 38
               target 39
               weight 1
        ]
        edge [
               source 77
               target 78
               weight 1
        ]
        edge [
               source 0
               target 46
               weight 1
        ]
        edge [
               source 60
               target 3
               weight 1
        ]
        edge [
               source 0
               target 68
               weight 1
        ]
        edge [
               source 14
               target 3
               weight 1
        ]
        edge [
               source 0
               target 5
               weight 1
        ]
        edge [
               source 59
               target 60
               weight 1
        ]
        edge [
               source 0
               target 65
               weight 1
        ]
        edge [
               source 0
               target 53
               weight 1
        ]
        edge [
               source 28
               target 29
               weight 1
        ]
        edge [
               source 0
               target 56
               weight 1
        ]
        edge [
               source 75
               target 3
               weight 1
        ]
        edge [
               source 0
               target 43
               weight 1
        ]
        edge [
               source 6
               target 2
               weight 1
        ]
        edge [
               source 30
               target 31
               weight 1
        ]
        edge [
               source 36
               target 3
               weight 1
        ]
        edge [
               source 0
               target 28
               weight 1
        ]
        edge [
               source 32
               target 33
               weight 1
        ]
        edge [
               source 39
               target 3
               weight 4
        ]
        edge [
               source 58
               target 33
               weight 1
        ]
        edge [
               source 0
               target 70
               weight 1
        ]
        edge [
               source 26
               target 3
               weight 1
        ]
        edge [
               source 0
               target 50
               weight 1
        ]
        edge [
               source 0
               target 37
               weight 1
        ]
        edge [
               source 29
               target 3
               weight 3
        ]
        edge [
               source 78
               target 3
               weight 1
        ]
        edge [
               source 0
               target 40
               weight 1
        ]
        edge [
               source 12
               target 3
               weight 1
        ]
        edge [
               source 0
               target 25
               weight 1
        ]
        edge [
               source 15
               target 3
               weight 1
        ]
        edge [
               source 0
               target 59
               weight 1
        ]
        edge [
               source 2
               target 3
               weight 4
        ]
        edge [
               source 51
               target 3
               weight 1
        ]
        edge [
               source 0
               target 63
               weight 1
        ]
        edge [
               source 0
               target 34
               weight 1
        ]
        edge [
               source 54
               target 3
               weight 1
        ]
        edge [
               source 53
               target 54
               weight 1
        ]
        edge [
               source 41
               target 3
               weight 2
        ]
        edge [
               source 46
               target 19
               weight 1
        ]
        edge [
               source 24
               target 3
               weight 1
        ]
        edge [
               source 0
               target 16
               weight 1
        ]
        edge [
               source 0
               target 9
               weight 1
        ]
        edge [
               source 0
               target 47
               weight 1
        ]
        edge [
               source 52
               target 39
               weight 1
        ]
        edge [
               source 17
               target 3
               weight 1
        ]
        edge [
               source 0
               target 69
               weight 1
        ]
        edge [
               source 68
               target 2
               weight 1
        ]
        edge [
               source 42
               target 29
               weight 1
        ]
        edge [
               source 0
               target 72
               weight 1
        ]
        edge [
               source 69
               target 3
               weight 1
        ]
        edge [
               source 1
               target 2
               weight 1
        ]
        edge [
               source 70
               target 71
               weight 1
        ]
        edge [
               source 3
               target 3
               weight 50
        ]
        edge [
               source 76
               target 73
               weight 1
        ]
        edge [
               source 0
               target 44
               weight 1
        ]
        edge [
               source 56
               target 57
               weight 1
        ]
        edge [
               source 47
               target 41
               weight 1
        ]
        edge [
               source 0
               target 66
               weight 1
        ]
        edge [
               source 45
               target 3
               weight 1
        ]
        edge [
               source 43
               target 31
               weight 1
        ]
        edge [
               source 9
               target 10
               weight 1
        ]
        edge [
               source 0
               target 38
               weight 1
        ]
        edge [
               source 31
               target 3
               weight 2
        ]
        edge [
               source 11
               target 12
               weight 1
        ]
        edge [
               source 0
               target 23
               weight 1
        ]
        edge [
               source 48
               target 49
               weight 1
        ]
        edge [
               source 67
               target 3
               weight 1
        ]
        edge [
               source 21
               target 22
               weight 1
        ]
        edge [
               source 0
               target 13
               weight 1
        ]
        edge [
               source 0
               target 48
               weight 1
        ]
        edge [
               source 4
               target 3
               weight 1
        ]
        edge [
               source 27
               target 8
               weight 1
        ]
        edge [
               source 57
               target 3
               weight 1
        ]
        edge [
               source 5
               target 2
               weight 1
        ]
]